export const SIGNIN = `/users/login`;
export const SIGNUP = `/users/register`;
export const BANNER = `/banner/read`;
export const CATEGORIES = `/category/read`;
export const CATEGORY = (id) => `/category/read/${id}`;
export const VIDEOS = `/video/read`;
export const VIDEO = (id) => `/video/read/${id}`;
export const SEARCH_VIDEO = (title) => `/video/search/${title}`;
export const VIDEOS_BY_CATEGORY = (categoryId) => `/video/read/videos/${categoryId}`;
export const SEND_MESSAGE = `/chat/create`;
export const MESSAGES = (userId) => `/chat/read/chat/${userId}`;
export const CMS_PAGES = `/cms/read`;
export const CMS_PAGE = (pageId) => `/cms/read/${pageId}`;
export const UPDATE_PROFILE = ``;
export const PROFILE = (userId) => ``;
export const UPDATE_USER = (userId) => `/users/${userId}`;
export const NOTIFICATION = ``;